[workspace]

resolver = "2"

members = [
  "solutions/d1",
  "solutions/d2",
  "solutions/d3",
  "solutions/d4",
  "solutions/d5",
  "solutions/d6",
  "solutions/d7",
  "solutions/d8",
  "solutions/d9",
  "solutions/d10",
]
