name: Workspace

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Check linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
